swagger: "2.0"
info:
  version: 1.0.0
  description: "This is a dentist service API"
  title: "ML dentist service API "
  contact:
    email: "k.singh.1@student.unsw.edu.au"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "dentist.swagger.io"
basePath: "/v1"
tags:
- name: "default"
  description: "Everything about dentist service"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"


schemes:
- "http"
paths:
  /dentists:
    get:
      tags:
      - "default"
      summary: "return all dentists"
      description: "You can ask about available dentist, timeslots, make booking and cancel booking"
      
      produces:
      - "application/json"
      
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              result:
                type: "string"
                example: [{d_id: "1", dentistName: "Dr. Manish", specialization: "Paediatric Dentistry", location: "Maroubra"},{d_id: "2", dentistName: "Dr. Virdi", specialization: "Orthodontics", location: "Eastlakes" },{d_id: "3", dentistName: "Dr. Oliver", specialization: "Oral Surgery", location: "Newtown" }]
              
        "500":
          description: "Internal server error"
          
  /dentists/{dentist_name}:
    get:
      operationId: get_dentist
      parameters:
        - name: dentist_name
          in: "path"
          type: string
          default: Dr. Virdi
          required: true
      summary: return dentist's information
      produces:
      - "application/json"
      responses:
        200:
          description: OK
          schema:
            type: "object"
            properties:
              result:
                type: "string"
                example: [{d_id: "1", dentistName: "Dr. Manish", specialization: "Paediatric Dentistry", location: "Maroubra"}]
              
        "500":
          description: "Internal server error"
    

             
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"